### ISSUE TITLE
Error: spawn EACCES

### ISSUE THREAD

**Issue by sudeepdk** [iurii-kyrylenko/hobbies#4]
> front-end-vue@1.0.0 dev /media/dk/A61EEFCD1EEF9499/sudeep_dk/2017/vuejs/hobbies/front-end-vue
> node build/dev-server.js

internal/child_process.js:319
    throw errnoException(err, 'spawn');
    ^

Error: spawn EACCES
    at exports._errnoException (util.js:1050:11)
    at ChildProcess.spawn (internal/child_process.js:319:11)
    at Object.exports.spawn (child_process.js:378:9)
    at module.exports (/media/dk/A61EEFCD1EEF9499/sudeep_dk/2017/vuejs/hobbies/front-end-vue/node_modules/opn/index.js:75:24)
    at Server.<anonymous> (/media/dk/A61EEFCD1EEF9499/sudeep_dk/2017/vuejs/hobbies/front-end-vue/build/dev-server.js:81:5)
    at Object.onceWrapper (events.js:293:19)
    at emitNone (events.js:86:13)
    at Server.emit (events.js:188:7)
    at emitListeningNT (net.js:1290:10)
    at _combinedTickCallback (internal/process/next_tick.js:77:11)
    at process._tickCallback (internal/process/next_tick.js:104:9)
    at Module.runMain (module.js:607:11)
    at run (bootstrap_node.js:423:7)
    at startup (bootstrap_node.js:147:9)
    at bootstrap_node.js:538:3

npm ERR! Linux 3.13.0-96-generic
npm ERR! argv "/home/dk/.nvm/v7.9.0/bin/node" "/home/dk/.nvm/v7.9.0/bin/npm" "run" "dev"
npm ERR! node v7.9.0
npm ERR! npm  v4.2.0
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! front-end-vue@1.0.0 dev: `node build/dev-server.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the front-end-vue@1.0.0 dev script 'node build/dev-server.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the front-end-vue package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node build/dev-server.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs front-end-vue
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls front-end-vue
npm ERR! There is likely additional logging output above.

**Comment by iurii-kyrylenko** [comment]
@sudeepdk,
Looks like the execute **permission is missed** when node.js attempts to open url in the default browser

**Comment by sudeepdk** [comment]
yes .. thanks
